<head>

<script type="text/javascript" src="<?php echo $baseUrl;?>/WebOne/public/script/jquery.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/WebOne/public/script/index.js"></script>
</head>
<body>
<div id="welcome">

    <div class="login" id="login" >
    <h1 id="login_head">
	健康<span>days</span>
	</h1>
    <div class="modal-body">
      <form class='form-signin' action="/WebOne/public/Login/login" method="post">
                    <div class="form-group">
                        <label class="control-label">账号</label>
                        <input type='email' id='inputEmail' name='account'class='form-control' placeholder='Email address' required autofocus>
                    </div>
                    <div class="form-group">
                        <label class="control-label">密码</label>
                        <input type='password' id='inputPassword' name='password' class='form-control' placeholder='Password' required>
                    </div>
                    <div class='checkbox'>
                        <label>
                            <input type='checkbox' value='remember-me'> 记住
                        </label>
                    </div>
                    <input type="submit" id="submit" name="submit" value="登陆"/>
       </form>
    </div>
    
      <div id="login_content">
         <p>还没有注册账号？<a href="/WebOne/public/Index/index?type=2">[立即注册]</a></p>
      </div>
      
     </div>

     
     <div class="register"  id="register" style="display: none;">
     
	 
	     <h1 id="reagister_head">注册账号</h1>

             <form class='form-signin' action="/WebOne/public/Login/register" method="post">           
                    <div class="form-group">
                        <label class="control-label">邮箱</label>
                        <input type='email' id='inEmail' name="account" class='form-control' placeholder='Email address' required autofocus>
                    </div>
                       <div class="form-group">
                        <label class="control-label">姓名</label>
                        <input type="text" id="inName" name="name" class="form-control" placeholder="Name" required>
                    </div>
                    <div class="form-group">
                        <label class="control-label">密码</label>
                        <input type='password' id='inPassword' name="password" class='form-control' placeholder='Password' required>
                    </div>
                    <div class="form-group">
                        <label class="control-label">验证码</label>
                        <input type="text" id="sureCode" class="form-control" name="code" placeholder="SureCode" required>
                        <img src="<?php echo $baseUrl;?>/WebOne/public/tool/validcode.php" style="width:100px;height:25px;" id="code"/>  
                        <a href="javascript:changeCode()">看不清，换一张</a>  
                    </div>   
                   <input type="submit" id="submit" name="submit" value="提交"/>                                
                </form>
       <div id="register content">
         <p>已有账号<a href="/WebOne/public/Index/index?type=1">[登陆]</a></p>
       </div>				
     </div>  
       
</div>

<script>

if(<?=$this->type?>==1)
{
showLogin();
}else if(<?=$this->type?>==2){
showRegister();	
}


function changeCode(){  
    document.getElementById("code").src = "<?php echo $baseUrl;?>/WebOne/public/tool/validcode.php?id="+Math.random();  
}  
</script>
</body>

