

<div id="welcome">

    <h1>健康<span>days</span></h1>


    <div id="login">
    
    <div class="modal-body">
      <form class='form-signin' action="Login/login" method="post">
                    <div class="form-group">
                        <label class="control-label">账号</label>
                        <input type='email' id='inputEmail' name='account'class='form-control' placeholder='Email address' required autofocus>
                    </div>
                    <div class="form-group">
                        <label class="control-label">密码</label>
                        <input type='password' id='inputPassword' name='password' class='form-control' placeholder='Password' required>
                    </div>
                    <div class='checkbox'>
                        <label>
                            <input type='checkbox' value='remember-me'> 记住
                        </label>
                    </div>
                     <input type="submit" id="submit" name="submit" value="登陆"/>
     
       </form>
     </div>
     
      <div id="content">
         <p>还没有注册账号？</p>
      
      
      </div>
      
     
     
     <div class="register" >
     
             <form class='form-signin' action="Login/register" method="post">
             
                    <div class="form-group">
                        <label class="control-label">邮箱</label>
                        <input type='email' id='inEmail' name="account" class='form-control' placeholder='Email address' required autofocus>
                    </div>
                       <div class="form-group">
                        <label class="control-label">姓名</label>
                        <input type="text" id="inName" name="name" class="form-control" placeholder="Name" required>
                    </div>
                    <div class="form-group">
                        <label class="control-label">密码</label>
                        <input type='password' id='inPassword' class='form-control' placeholder='Password' required>
                    </div>
                    <div class="form-group">
                        <label class="control-label">验证码</label>
                        <input type="text" id="sureCode" class="form-control" name="code" placeholder="SureCode" required>
                    </div>
                    
                    
                   <input type="submit" id="submit" name="submit" value="提交"/>
                                  
                </form>
     
         
     
     </div>
     
     <div id="content1" style="display: none;">
         <p>已经拥有密码了吗？</p>
      
      
      </div>
 
          
        
    </div>
    
</div>