<h1>添加活动</h1>
<form action='/WebOne/public/activity/addactivity' method="post">
<table>
<tr><td>name</td><td><input type='text' name='name'/></td></tr>
<tr><td>content</td><td><input type='text' name='content'/></td></tr>
<tr><td>begin</td><td><input type='text' name='begin'/></td></tr>
<tr><td>end</td><td><input type='text' name='end'/></td></tr>
<tr><td><input type='submit' value='add'/></td><td><input type="reset" value="reset"/></td></tr>
</table>
</form>