<head>
<link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/bootstrap.min.css">
<script type="text/javascript" src="<?php echo $baseUrl;?>/WebOne/public/script/jquery.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/WebOne/public/script/bootstrap.min.js"></script>
<link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/nav.css">
</head>


<h1>添加活动</h1>
<form action='/WebOne/public/activity/addactivity' method="post">
<table>
<tr><td>name</td><td><input type='text' name='name'/></td></tr>
<tr><td>content</td><td><input type='text' name='content'/></td></tr>
<tr><td>begin</td><td><input type='text' name='begin'/></td></tr>
<tr><td>end</td><td><input type='text' name='end'/></td></tr>
<tr><td><input type='submit' value='add'/></td><td><input type="reset" value="reset"/></td></tr>
</table>
</form>