<head>
<link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/proposalindex.css">

</head>
<body>
        <div id=proposal_nav>
            <p id=proposal_nav_title>问题中心</p>
            <ul class="nav nav-pills nav-stacked" id="id_proposal_nav">
                <li><a href="/WebOne/public/proposal">问题列表</a></li>
                <li><a href="/WebOne/public/proposal/newpost">我要提问</a></li>
                <li><a href=/WebOne/public/proposal/myquestion>我的问题</a></li>
                <li class="active"><a href=#>健康专家</a></li>
            </ul>
        </div>
        
        <div id="id_health_panel">
          <div class="panel panel-success" id="id_health_contentpanel">
              <p id="id_health_panel_title">专家列表：</p>
               <?php  foreach ($this->result as $info)  { ?>
              <div id=id_health_part>
                 <div class="userHeaderImg" id=id_health_portarit>
                   <a href="#">
                   <img class=img-circle src=<?=$info[image]?>  border=0 width=100 height=100 />
                   </a>
                 </div> 
                 <div id=id_health_info>
                   <a href=/WebOne/public/proposal/expertdetail?expertid=<?=$info[userid]?>><p id=id_health_name><?=$info[name]?></p></a>
                   <p id=id_health_detail><?=$info[info]?></p>
                 </div>
                 <div>
                      <p id=id_expert_focus>关注数：<?=$info[concern]?></p>
                     <?php if($info[Isconcern]==0){?>
                     <input type="submit"  class="btn btn-default" id=id_expert_focus hidefocus="true" onclick="window.location.href='/WebOne/public/Proposal/concern?expertid=<?=$info[userid]?>&location=0'"value="关注" ">     
                     <?php } else {?>
                     <input type="submit"  class="btn btn-default" id=id_expert_focus hidefocus="true" onclick="window.location.href='/WebOne/public/Proposal/concern?expertid=<?=$info[userid]?>&location=0'"value="已关注" ">     
                     <?php }?>
                     
                 </div>               
              </div>
              <?php }?>
                <div id=id_expert_page>
              <?php if($this->page>0){?>
             <a  href="/WebOne/public/proposal/expert?page=<?=$this->page-1?>">上一页</a>
           <?php }?>         
             
            <?php foreach ($this->count as $index) {?>   
            <?php if($index==($this->page+1)){?>
             <span id=current><?=$index?></span>                 
            <?php } else {?>
           <a id=page href="/WebOne/public/proposal/expert?page=<?=$index-1?>"><?=$index?></a>   
            <?php } }?>               
             <?php if($this->page<8){?>
             <a  href="/WebOne/public/proposal/expert?page=<?=$this->page+1?>">下一页</a>
             <?php }?>                          
               </div> 
          </div>
        </div>
        
        
        
                
</body>