<head>
<link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/proposalindex.css">
</head>
<body>
   <div id="id_panel">
     <div class="panel panel-success" id="id_contentpanel">
      <div class="panel-heading text-center" id=panel-heading>
      <h4 class="panel-title">问题</h4>
     </div>   
       <div id=id_content>
         <?php foreach ($this->result as $info) {?>
           <div id=id_content_part>
             <div id=part_content>
               <p id=part_content_title>
                  <a href='/WebOne/public/proposal/show?questionid=<?=$info['id']?>'><?= $info['title'] ?></a>
               </p>
             
               <div id=part_content_info>
                 <p id=part_content_question>
                   <span style="font-size:24px;">&nbsp;&nbsp;&nbsp;</span>
                 0.0我想问一个问题啊，问什么好呢，我不知道呀；但是还是要问。0.0别烦我 我在写Web呢 你狗带</p>
                 <p id=part_content_answer>
                                                            回答数:<?= $info['answernum'] ?>
                 </p>
                 <p id=part_content_time>
                                                            发表时间:<?= $info['time'] ?>
                 </p>
                 <p id=part_content_name>
                                                              作者 :<?= $info['uname'] ?>
                 </p>
               </div>
             </div>
             <div id=part_join>
             </div>
           </div>  
           <hr id=id_line></hr>
         <?php }?>
         
           <div id=id_content_page>
                      
           </div>        
            
       </div>       
     </div>   
   </div>
 <script>
 </script>
</body>