<head>
<link rel="stylesheet" href="/WebOne/public/css/bootstrap.min.css">
<script type="text/javascript" src="/WebOne/public/script/jquery.js"></script>
<script type="text/javascript" src="/WebOne/public/script/bootstrap.min.js"></script>
<script type="text/javascript" src="/WebOne/public/script/slider.js"></script>
<link rel="stylesheet" href="/WebOne/public/css/nav.css">
<link rel="stylesheet" href="/WebOne/public/css/proposalindex.css">
</head>





<body>
   <div id="id_panel">
     <div class="panel panel-success" id="id_contentpanel">
      <div class="panel-heading">
      <h3 class="panel-title">问题</h3>
     </div>   
       <div id=id_content>
         <?php foreach ($this->result as $info) {?>
           <div id=id_content_part>
           <div id=part_img>
             <img class=img-rounded src="<?php echo $baseUrl;?>/WebOne/public/image/11.jpg" border=0 width=120 height=80 />
             </div>
             <div id=part_content>
               <p id=part_content_title>
                  <a href='/WebOne/public/proposal/show?questionid=<?=$info['id']?>'><?= $info['title'] ?></a>
               </p>
               <div id=part_content_time>
                 <p id=part_content_begin>
                   Answers:<?= $info['answernum'] ?>
                 </p>
                 <p id=part_content_end>
                   Time :<?= $info['time'] ?>
                 </p>
                 <p id=part_content_end>
                   By :<?= $info['uname'] ?>
                 </p>
               </div>
             </div>
             <div id=part_join>
                
             </div>
           </div>  
         <?php }?>
         
           <div id=id_content_page>
           <?php if($this->page>0){?>
             <a  href="/WebOne/public/Activity/index?page=<?=$this->page-1?>">上一页</a>
           <?php }?>         
             
         <?php foreach ($this->count as $index) {?>   
            <?php if($index==($this->page+1)){?>
             <span id=current><?=$index?></span>                 
            <?php } else {?>
           <a id=page href="/WebOne/public/Activity/index?page=<?=$index-1?>"><?=$index?></a>   
            <?php } }?>               
             <?php if($this->page<8){?>
             <a  href="/WebOne/public/Activity/index?page=<?=$this->page+1?>">下一页</a>
             <?php }?>                       
           </div>        
            
       </div>       
     </div>   
   </div>
 <script>
 new slider({id:'slider'});
 </script>
</body>