<script type="text/javascript">
<!--
	//5000表示每隔5秒去调用;
	//window.setInterval("sendRequest()",5000);//现在注释掉 等界面完工再启用
	
	//定义一个http_request
	var http_request;
	var http_request_foraddanswer;
	
	//发送请求到服务器
	function sendRequest(questionid){
			//创建ajax引擎.
			if(window.ActiveXObject){
				http_request=new ActiveXObject("Microsoft.XMLHTTP");
			}else{				
				http_request=new XMLHttpRequest();
			}
			
			//如果ajax引擎创建ok
			if(http_request){				
				var url="/WebOne/public/tool/getAllAnswer.php?questionid="+questionid;				
				http_request.open("GET",url,true);	
				http_request.onreadystatechange=function deal(){
					
					var res=http_request.responseText;
					if(http_request.readyState==4){
						if(http_request.status==200){
							if(res=="err"){
								window.alert("服务器崩溃");
							}
							else{
								//需要改变的界面代码
								//document.getElementById
								window.alert(res);
							}
							
						}
					}


				};
				
				http_request.send();				
			}		
	}

	function sendAddNewAnswerRequest(){
		
		//创建ajax引擎.
		if(window.ActiveXObject){
			http_request_foraddanswer=new ActiveXObject("Microsoft.XMLHTTP");
		}else{				
			http_request_foraddanswer=new XMLHttpRequest();
		}
		
		//如果ajax引擎创建ok
		if(http_request_foraddanswer){				
			var url="/WebOne/public/tool/addnewanswer.php";//处理数据的php
			http_request_foraddanswer.open("POST",url,true);
			http_request_foraddanswer.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
			http_request_foraddanswer.onreadystatechange=function adddeal(){
				if(http_request_foraddanswer.readyState==4){
					if(http_request_foraddanswer.status==200){
						var res=http_request_foraddanswer.responseText;window.alert(res);
						if(res=="err"){
							window.alert("服务器崩溃");
						}
						else{
							//需要改变的界面代码
							//document.getElementById
						}
					
					}
				}
			};
			$data="acontent=aaaaaa&replyid=1&userid=1&questionid=1&inform_userid=1";//更新的数据
			http_request_foraddanswer.send($data);			
		}		
}
-->
</script>
<head>
<link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/proposalindex.css">
</head>
<body>
      <div id=proposal_nav>
           <p id=proposal_nav_title>问题中心</p>
              <ul class="nav nav-pills nav-stacked" id="id_proposal_nav">  
               <li ><a href=/WebOne/public/proposal>问题列表</a></li>
               <li ><a href="/WebOne/public/proposal/newpost">我要提问</a></li>
               <li><a href="/WebOne/public/proposal/myquestion">我的问题</a></li>
               <li><a href="/WebOne/public/proposal/expert">健康专家</a></li>
              </ul>
         </div>


<div id=id_panel>
  <div class="panel panel-success" id="id_contentpanel">
      <div class="panel-heading text-center" id=panel-heading>
      <h4 class="panel-title"><?= $this->result['title'] ?></h4>
     </div> 
      <div id=id_question_contents>
       <span style="font-size:24px;">&nbsp;&nbsp;&nbsp;</span>
       <p id=id_question_name>
       <img class=img-circle src=/WebOne/public/image/head/1.jpg  border=0 width=30 height=30 />
       <a>H77</a>
       </p>
       <p id=id_question_time><?= $this->result['time'] ?></p>
       <p id=id_question_content>
       <span style="font-size:24px;">&nbsp;&nbsp;&nbsp;</span>
       <?= $this->result['content'] ?>哎，心好累好累，真的好累，怎么办啊，
       心好累好累，真的好累，怎么办啊心好累好累，真的好累，怎么办啊</p>
       <p id=id_question_answers>       
       <?= $this->result['answernum'] ?>个回答
       </p>
       
     <input  type="submit"  class="btn btn-default"  id="question" hidefocus="true" onclick="sendRequest(5);" value="回答 " >          
      </div>      
      
     
     <div id=id_content>
        <hr id=id_reply_line></hr>
      <?php foreach ($this->answers as $info) {?>
       <div id=id_reply>
        <p id=part_reply_content><?= $info['content'] ?> </p>
        <p id=part_reply_answers>
        <a>评论  </a>|
        <input  type="submit"  class="btn btn-default"  id="submit" hidefocus="true" value="赞   <?= $info['agrees'] ?>" >        
        </p>
        <p id=part_reply_time>
         <?= $info['time'] ?>
        </p>
        <p id=part_reply_name>
        <img class=img-circle src=/WebOne/public/image/woman.png  border=0 width=25 height=25 />
        <a><span id=reply_username><?= $info['name'] ?></span></a>
        </p>       
        </div>
      <hr id=id_reply_line></hr>     
      <?php }?>
       </div>
   </div>
</div>
</body>


