
<div class="row">
<div class="col-md-6 col-md-offset-1" id="nav_home" >
<ul class="nav nav-tabs" >
<li class="li" id="lis"><a href=#>首页</a></li>
<li class="li" id="lis"><a href=#>健康</a></li>
<li class="li" id="lis"><a href=#>运动</a></li>
<li class="li" id="lis"><a href=#>活动</a></li>
<li class="li" id="lis"><a href=#>建议</a></li>
<div class="col-md-2 col-md-offset-1">
<div id="pos">
<li class="dropdown" >
<a class="dropdown-toggle" data-toggle="dropdown" href=#>
       <?=$this->info[0][name]?>
       <span class="caret"></span>
     </a>
        <ul class="dropdown-menu">
         <li class="divider"></li>
         <li class="li"><a href="/WebOne/public/Home/userinfo?id=<?=$this->info[0][id]?>">个人设置</a></li>
         <li class="li"><a href=#>退出登录</a></li>
        </ul>
       </li>
      </div>
     </div>
    
   </ul>   
  </div>
 </div>