<head>   
   <meta charset="UTF-8">
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/home.css">  
    <script type="text/javascript" src="<?php echo $baseUrl;?>/WebOne/public/script/home.js"></script> 
</head>

<body>
    <div class="container">
    <div id="userHeader">
     <div class="row" >
       <div class="userHeaderImg">
        <a href="#">
          <img class=img-circle src=<?=$this->result[0][image]?>  border=0 width=150 height=150 />
        </a>
       </div>
        <div id="userinfo">
    	   <div>
    	     <p class=word>姓名：<?=$this->result[0][name]?></p>
    	     <p class=word>职业：<?=$this->result[0][work]?></p>
    	     <p class=word>关注人数：</p>
    	     <p class=word><?=$this->result[0][concern]?></p>   
    	   </div>
       </div>
      </div>
    </div>
    
    <div id="id_top_panel"   >
       <div class="panel panel-success" id="id_top_contentpanel" >
          <p id="id_top_panel_title">咨询答复</p>
        <?php  foreach ($this->responses as $info)  { ?>
         <div id=id_advice_reply>
             <div id=id_advice_title>
              <p id=id_advice_titleword><?=$info[title]?> &nbsp&nbsp&nbsp 提问:<?=$info[name]?></p>
             </div>
             <div id=id_advice_touser>
             <p>回复 <a ><?=$info[name]?></a>:</p>
             </div>
             <div id=id_advice_content>
             <p><?=$info[response]?></p>
             </div>
             <div id=id_advice_time>
              <p><?=$info[time]?></p>
             </div>
             <hr id=id_myreply_line></hr>
         </div>
         <?php }?>      
       </div>
     </div>     
     <div id="id_panel"  >
       <div class="panel panel-success" id="id_contentpanel" >
           <p id="id_top_panel_title">咨询列表</p>
            <div id=id_advice_question>
               <?php  foreach ($this->question as $info)  { ?>
               <div id=id_question_part>
               <a href=/WebOne/public/home/experthome?expertid=10&type=1&questionid=<?=$info[id]?>><p id=id_question_titleword><?=$info[title]?></p></a>
               <p id=id_question_name>提问:<?=$info[name] ?></p>
               <p id=id_question_time><?=$info[time]?></p>    
               </div>
               <?php }?>           
            </div>
        </div>  
     </div>
     <div id="id_question_panel" style="display: none;">
       <div class="panel panel-success" id="id_question_contentpanel" >
        <p id="id_question_panel_title" class=aword><?=$this->question[0][title]?></p>
        <p id="id_question_panel_content" class=word>&nbsp&nbsp&nbsp&nbsp<?=$this->question[0][question]?></p>
        <form action="/WebOne/public/home/reply" method=post>
          <p id=id_question_panel_explain>关于问题的解答</p>
          <textarea id=id_question_panel_explaintext name='context'>
          </textarea>
        <input type="submit" class="btn btn-default" id="question_bt" name="reply"   value="回复"/>
        </form>
         <input type="submit" class="btn btn-default" id="question_bt1" name="reply" onclick="window.location.href='/WebOne/public/home/experthome?expertid=<?=$this->expertid?>'"  value="返回"/>  
        </div>
     </div>
     
      <script>
     if(<?=$this->type?>==0)
     {
     showmain();
     }else if(<?=$this->type?>==1){
     showquestion();	
     }     
     </script>           
</body>