<head>   
   <meta charset="UTF-8">
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/home.css">   
    <title>home</title>
</head>

<body>
    <div class="container">
    <div id="userHeader">
     <div class="row" >
       <div class="userHeaderImg">
        <a href="#">
          <img class=img-circle src=/WebOne/public/image/head/2.jpg  border=0 width=150 height=150 />
        </a>
       </div>
        <div id="userinfo">
    	   <div>
    	     <p class=word>姓名：Krystal</p>
    	     <p class=word>职业：健身教练</p>
    	     <p class=word>联系电话：</p>
    	     <p class=word>15850590186</p>
    	     <a id=id_experthome_detail><span class=aword >详细信息</span></a>
    	     <a id=id_experthome_question><span class=aword >咨询</span></a>    	     
    	   </div>
       </div>
      </div>
    </div>
    
    <div id="id_top_panel">
       <div class="panel panel-success" id="id_top_contentpanel">
          <p id="id_top_panel_title">咨询答复</p>
         <div id=id_advice_reply>
             <div id=id_advice_title>
              <p id=id_advice_titleword>为什么我运动经常会抽筋?</p>
              <p id=id_advice_name>提问:H77</p>
             </div>
             <div id=id_advice_touser>
             <p>回复 <a>H77</a>:</p>
             </div>
             <div id=id_advice_content>
             <p>锻炼前要适当热身，以免产生身体的不适.建议每天持续锻炼时间不要超过1h，要多次锻炼</p>
             </div>
             <div id=id_advice_time>
              <p>2015/10/30 21:41</p>
             </div>
             <hr id=id_myreply_line></hr>
         </div>
       </div>
     <div>
     
     <div id="id_panel">
       <div class="panel panel-success" id="id_contentpanel">
           <p id="id_top_panel_title">咨询列表</p>
            <div id=id_advice_question>
               <div id=id_question_part>
               <p id=id_question_titleword>为什么我运动经常会抽筋?(已答复)</p>
               <p id=id_question_name>提问:H77</p>
               <p id=id_question_time>2015/10/31 13:33</p>
               </div>
               <div id=id_question_part>
               <p id=id_question_titleword>教练你是怎样健身的呢?(未回答)</p>
               <p id=id_question_name>提问:H77</p>
               <p id=id_question_time>2015/10/31 13:33</p>
               </div>
               <div id=id_question_part>
               <p id=id_question_titleword>教练怎样保持体形?(未回答)</p>
               <p id=id_question_name>提问:H77</p>
               <p id=id_question_time>2015/10/31 13:33</p>
               </div>
               <div id=id_question_part>
               <p id=id_question_titleword>为什么我运动经常会抽筋?(未回答)</p>
               <p id=id_question_name>提问:H77</p>
               <p id=id_question_time>2015/10/31 13:33</p>
               </div>
            </div>
       
       </div>
     <div>
</body>