<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/home.css">
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/bootstrap.min.css">
    <script type="text/javascript" src="<?php echo $baseUrl;?>/WebOne/public/script/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $baseUrl;?>/WebOne/public/script/bootstrap.min.js"></script>
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/WebOne/public/css/nav.css">
    
    <title>home</title>
</head>


<body>
  
  
<div class="container">
<div id="userHeader">
 <div class="row" >
   <div class="userHeaderImg">
    <a href="#">
       <?php         
       echo "<img class=img-circle src=$this->path  border=0 width=150 height=150 />";
       ?>    
    </a>
   </div>
    <div id="userinfo">
	 <p id="userinfo_word">欢迎<?php  echo $this->info[0][name] ?></p>
	 <a href="/WebOne/public/Home/userinfo?id=<?=$this->info[0][id]?>"><?php  echo $this->info[0][name] ?></a>
   </div>
  </div>
</div>

<div class="content">
     <div class="panel panel-default ">
       <div class="panel-body">
         <h2><span>健康</span>days</h2> 
       </div>
     </div>
     <div class="panel panel-default ">
      </br>
     <div class="btn-group" data-toggle="buttons" >
       <label class="btn  btn-success">
         <input type="radio" name="options" id="option1"> 分享
       </label>
       <label class="btn  btn-success">
         <input type="radio" name="options" id="option2"> 动态
       </label>
     </div>	
     
     　　<div style="border-bottom:1px solid #ccc"></div>
     </br>
     <?php  
     $i=0;
     while($i<5)
     {
         $i++;
         echo "<div style=\"border-bottom:1px dashed #ccc\">"; 
         echo "<tr><p>韩奇祺到此一游哈哈哈</p>";   
         echo "<p>韩奇祺到此一游哈哈哈</p></tr>";
         echo "</div>";
     }
                 
     ?>
     </br>
     
    </div>
</div>

</div>
</body>